import AllProducts from "@/components/AllProducts";
import HomePageProducts from "@/components/HomePageProducts";
import SubHeader from "@/components/SubHeader";
import Head from "next/head";

// import { Inter } from "@next/font/google";
// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      {/* Should include meta tags in every page, for seo */}
      <Head>
        <title>Audiophile | Presh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        {/* <NavMenu /> */}
        <SubHeader />
        <AllProducts />
        <HomePageProducts />
      </>
    </>
  );
}
